apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mydiet
  name: mydiet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydiet
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mydiet
    spec:
      containers:
      - image: harbor.wbl.com/fitness/mydiet:latest
        name: mydiet
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz-seoul
        env:
        - name: DB_URI
          valueFrom:
            configMapKeyRef:
              name: fitness-cm
              key: DB-URI
        - name: DB_USER_NAME
          valueFrom:
            secretKeyRef:
              name: fitness-sc
              key: DB-USER-NAME
        - name: DB_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fitness-sc
              key: DB-USER-PASSWORD
        resources: {}
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
          type: ""
        name: tz-seoul
status: {}
---
