apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mydiet
  name: mydiet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydiet
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mydiet
    spec:
      containers:
      - image: harbor.wbl.com/fitness/mydiet:latest
        name: mydiet
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz-seoul
        env:
        - name: DB_URI
          value: mysql:3306
        - name: DB_USER_NAME
          value: byung8
        - name: DB_USER_PASSWORD
          value: 1q2w3e4r5t
        resources: {}
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
          type: ""
        name: tz-seoul
status: {}
---
